### ISSUE TITLE
analyzer that can check for all sequence IDs in a trigger record

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/rawdatautils#14]
We need an analyzer that can check the completeness of all sequence IDs: that is, all sequence IDs have been written out to the file(s). Ideas on needs...

* Should look at a trigger record in a file, and see how many sequence IDs there are.
* Should then see through a given file or list of files and track the number of sequence IDs that are there.
* At the end, should print out, for each trigger record, what sequence IDs are not present and if there are any duplicates.

As an additional option/check, it would be good to see that for each sequence ID, that it contains the same number of fragments. Further, that for each fragment, that for the wibs it contains the same number of frames per fragment.

**Comment by bieryAtFnal** [comment]
The commands below run rather slowly, but I've used them check for the presence of the expected number of fragments, and their expected size:
```
ls -1 *17946*.hdf5 | xargs -n 1 HDF5LIBS_TestDumpRecord | grep WIB | wc -l 
<returns 81920 (32 triggers, 10 links, 256 sequences => 81920)>

ls -1 *17946*.hdf5 | xargs -n 1 HDF5LIBS_TestDumpRecord | grep WIB | grep -v 3866696
<returns nothing>
```

**Comment by wesketchum** [comment]
file_quality_checker does it now. Closing.
