### ISSUE TITLE
wib2decoder / other decoders should unpack geoid to geoinfo

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/rawdatautils#7]
We should have a method for unpacking the GeoID `uint64_t` into a GeoInfo object that can more easily/straightforwardly be interpreted. This probably would make use of an interface in hdf5libs. Looking at detchannelmaps, we'd want to use something like `parse_geoid`, but that requires the `HardwareMapService` which may need to be setup from info in the raw data file metadata?

**Comment by bieryAtFnal** [comment]
@wesketchum , the geoid <--> GeoInfo methods in the HardwareMapService are static, so we wouldn't need to construct an instance of the HardwareMapService class to use them.  So, I suspect that we wouldn't need to "setup from info in the raw data file metadata".  Do you agree?

If so, then it seems reasonable to provide a utility method somewhere in hdf5libs (C++ and Python) that passes along the geoid <--> GeoInfo functionality, and raw data utilities could make use of that.  Sound reasonable?

**Comment by wesketchum** [comment]
That does sound reasonable to me!

**Comment by glehmannmiotto** [comment]
I don't know if this is a related request: it would be useful to be able to optionally pass a hw map file to the wib2decoder utility, in order to be able to validate that the sourceid - geoid mapping is really as intended when looking inside the data content

**Comment by wesketchum** [comment]
@glehmannmiotto at first thought, I'd suggest making that a separate request in rawdatautils. That requires more work on utilities parsing the hardware map for analysis, and then comparing against what's in the file (using something like this added functionality, ideally)

**Comment by alessandrothea** [comment]
I am confused. `GeoInfo` and`GeoID` seem to carry the same information, the only difference being that `GeoInfo` organizes in 4 `uint16_t`. If this is how `GeoID` bits are supposed to be used in the first place, why isn't the `GeoID` structure as such? Why is `GeoInfo` part of `HardwareMap`?
They seem completely redundant constructs so rather that spreading their use we should try reducing the underlying ambiguity

**Comment by wesketchum** [comment]
Done.
